# Site settings
title: Seattle Lung Project
header-img: img/home-bg.jpg
email: seattlelungproject@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://raesian.github.io"
twitter_username: SeattleLung
facebook_username:  SeattleLungProject

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
